name: Update Geo Flood Data

on:
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h UTC
  workflow_dispatch:      # Permet aussi de déclencher manuellement

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Update_geo_script/requirements.txt

    - name: Run update script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python Update_geo_script/update_geo_data.py
